<?php

namespace Database\Seeders;

use App\Models\ClenroPileupReport;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class ClenroPileupReportSeeder extends Seeder
{
    /**
     * Run the database seeds for CLENRO Historical Garbage Pile-Up Reports.
     * Scope: Cagayan de Oro City - Barangay 1 to 40, Cogon Market, and Carmen Market.
     */
    public function run(): void
    {
        // Clear previous records if table exists
        ClenroPileupReport::truncate();

        $data = [
            // ==========================================
            // COGON MARKET SPECIAL COMMERCIAL ZONE
            // ==========================================
            [
                'incident_code' => 'CDO-CGN-2024-0112',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 34,
                'specific_landmark' => 'Yacapin St. Entrance (Vegetable & Fruit Section)',
                'latitude' => 8.4776100,
                'longitude' => 124.6482100,
                'incident_date' => '2024-01-12 21:30:00',
                'cleared_date' => '2024-01-13 04:15:00',
                'turnaround_hours' => 6.75,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 18.5,
                'estimated_tonnage' => 7.4,
                'severity' => 'critical',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Dispatched 2 compactors for immediate post-closing sweep. Cleaned curb and disinfected trading lane.',
                'decision_recommendation' => 'Mandate vegetable stallholders to bag trimmings prior to 8:30 PM closing. Establish dedicated 9:00 PM compactor run.',
                'reported_by' => 'CLENRO Market Inspector #04',
            ],
            [
                'incident_code' => 'CDO-CGN-2024-0428',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 33,
                'specific_landmark' => 'J.R. Borja St. Frontage (Near Capt. Vicente Roa Intersection)',
                'latitude' => 8.4781500,
                'longitude' => 124.6476500,
                'incident_date' => '2024-04-28 22:10:00',
                'cleared_date' => '2024-04-29 11:30:00',
                'turnaround_hours' => 13.33,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 14.2,
                'estimated_tonnage' => 5.6,
                'severity' => 'high',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'collection_truck_breakdown',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'KDG-8821',
                'status' => 'resolved',
                'clenro_action_taken' => 'Contractor primary compactor experienced hydraulic failure; CLENRO ordered backup dump truck dispatch at 9:00 AM.',
                'decision_recommendation' => 'Contractor required to maintain stand-by replacement vehicle within 1 hour radius of Cogon Commercial District.',
                'reported_by' => 'Barangay 33 Sanitation Officer',
            ],
            [
                'incident_code' => 'CDO-CGN-2024-0827',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 39,
                'specific_landmark' => 'Capt. Vicente Roa St. Night Market Vendor Strip',
                'latitude' => 8.4768900,
                'longitude' => 124.6489500,
                'incident_date' => '2024-08-27 23:45:00',
                'cleared_date' => '2024-08-28 05:00:00',
                'turnaround_hours' => 5.25,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 24.0,
                'estimated_tonnage' => 9.8,
                'severity' => 'critical',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9014',
                'status' => 'resolved',
                'clenro_action_taken' => 'Higalaay Festival peak shopping crowd. Deployed two emergency open haulers plus 12 city eco-sweepers.',
                'decision_recommendation' => 'Allocate 30% additional hauling capacity during annual Higalaay Festival week (Aug 24-29). Install 10 high-capacity mobile bins.',
                'reported_by' => 'CLENRO Festival Monitoring Taskforce',
            ],
            [
                'incident_code' => 'CDO-CGN-2024-1223',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 34,
                'specific_landmark' => 'Osmeña St. Commercial Alley & Fruit Stalls',
                'latitude' => 8.4772000,
                'longitude' => 124.6493000,
                'incident_date' => '2024-12-23 20:00:00',
                'cleared_date' => '2024-12-24 07:30:00',
                'turnaround_hours' => 11.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 28.5,
                'estimated_tonnage' => 11.4,
                'severity' => 'critical',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Holiday fruit deliveries created 3-meter high mound on pedestrian lane. Cleared via back-to-back truck trips.',
                'decision_recommendation' => 'Implement mandatory pre-sorted organic waste drop-off zones during December 15-31 holiday peak.',
                'reported_by' => 'Cogon Market Administration',
            ],
            [
                'incident_code' => 'CDO-CGN-2025-0314',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 40,
                'specific_landmark' => 'Guillermo St. Loading Bay & Fish Section',
                'latitude' => 8.4764000,
                'longitude' => 124.6479000,
                'incident_date' => '2025-03-14 18:30:00',
                'cleared_date' => '2025-03-15 09:00:00',
                'turnaround_hours' => 14.50,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 12.0,
                'estimated_tonnage' => 5.2,
                'severity' => 'high',
                'waste_category' => 'wet_fish_meat_waste',
                'root_cause' => 'delayed_contractor_dispatch',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'KDG-8821',
                'status' => 'resolved',
                'clenro_action_taken' => 'Putrid fish entrails left overnight. Contractor penalized under Section 14 of City Sanitation Agreement.',
                'decision_recommendation' => 'Impose ₱15,000 contractor liquidated damages for putrescible fish waste SLA breach over 12 hours.',
                'reported_by' => 'CLENRO Eco-Warden #11',
            ],
            [
                'incident_code' => 'CDO-CGN-2025-0718',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 33,
                'specific_landmark' => 'J.R. Borja St. Corner Yacapin St.',
                'latitude' => 8.4780500,
                'longitude' => 124.6481000,
                'incident_date' => '2025-07-18 19:15:00',
                'cleared_date' => '2025-07-19 18:30:00',
                'turnaround_hours' => 23.25,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 16.8,
                'estimated_tonnage' => 6.9,
                'severity' => 'critical',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'monsoon_drainage_blockage',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Flash rain caused uncollected market garbage to float into drainage inlets. Heavy clearing performed.',
                'decision_recommendation' => 'Elevate waste staging platform above curb level to prevent washout during monsoon downpours.',
                'reported_by' => 'CLENRO Drainage Oversight Team',
            ],
            [
                'incident_code' => 'CDO-CGN-2025-1011',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 34,
                'specific_landmark' => 'Yacapin St. Commercial Alley (Mid-Block)',
                'latitude' => 8.4778000,
                'longitude' => 124.6484500,
                'incident_date' => '2025-10-11 21:00:00',
                'cleared_date' => '2025-10-12 03:30:00',
                'turnaround_hours' => 6.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 15.0,
                'estimated_tonnage' => 6.0,
                'severity' => 'high',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'unauthorized_vendor_dumping',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9014',
                'status' => 'resolved',
                'clenro_action_taken' => 'Issued 4 citation tickets under CDO City Ordinance No. 13378-2018 to non-compliant transient vendors.',
                'decision_recommendation' => 'Deploy 2 night-patrol Eco-Wardens between 7:00 PM and 10:00 PM to apprehend illegal dumpers.',
                'reported_by' => 'CLENRO Eco-Warden #07',
            ],
            [
                'incident_code' => 'CDO-CGN-2026-0215',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 39,
                'specific_landmark' => 'Capt. Vicente Roa St. Dry Goods Perimeter',
                'latitude' => 8.4769200,
                'longitude' => 124.6488000,
                'incident_date' => '2026-02-15 20:30:00',
                'cleared_date' => '2026-02-16 02:45:00',
                'turnaround_hours' => 6.25,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 11.2,
                'estimated_tonnage' => 4.5,
                'severity' => 'moderate',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Night route collection completed smoothly on scheduled time.',
                'decision_recommendation' => 'Maintain current 8:30 PM collection dispatch protocol for dry goods strip.',
                'reported_by' => 'CLENRO Night Inspector #02',
            ],

            // ==========================================
            // CARMEN MARKET SPECIAL COMMERCIAL ZONE
            // ==========================================
            [
                'incident_code' => 'CDO-CRM-2024-0219',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Carmen Public Market - Vamenta Blvd Frontage',
                'latitude' => 8.4831000,
                'longitude' => 124.6364000,
                'incident_date' => '2024-02-19 19:40:00',
                'cleared_date' => '2024-02-20 03:00:00',
                'turnaround_hours' => 7.33,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 14.5,
                'estimated_tonnage' => 5.8,
                'severity' => 'high',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4105',
                'status' => 'resolved',
                'clenro_action_taken' => 'Compactor cleared 14.5 m3 of organic trimmings from Vamenta street vendors before morning traffic.',
                'decision_recommendation' => 'Establish permanent segregated bio-waste holding pens inside market perimeter.',
                'reported_by' => 'Carmen Market Supervisor',
            ],
            [
                'incident_code' => 'CDO-CRM-2024-0610',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Seriña St. Wet Section & Fish/Poultry Alley',
                'latitude' => 8.4828000,
                'longitude' => 124.6358000,
                'incident_date' => '2024-06-10 18:00:00',
                'cleared_date' => '2024-06-11 10:15:00',
                'turnaround_hours' => 16.25,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 11.0,
                'estimated_tonnage' => 4.8,
                'severity' => 'critical',
                'waste_category' => 'wet_fish_meat_waste',
                'root_cause' => 'delayed_contractor_dispatch',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'KDG-8821',
                'status' => 'resolved',
                'clenro_action_taken' => 'Severe odor complaints from residents. Hauler failed afternoon pickup. Warning notice issued.',
                'decision_recommendation' => 'Enforce penalty clause for untreated wet poultry/fish waste standing over 8 hours.',
                'reported_by' => 'CLENRO Health & Sanitation Inspector',
            ],
            [
                'incident_code' => 'CDO-CRM-2024-0828',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Carmen Bridge Foot (Ysalina Bridge Approach Corridor)',
                'latitude' => 8.4839000,
                'longitude' => 124.6391000,
                'incident_date' => '2024-08-28 21:15:00',
                'cleared_date' => '2024-08-29 04:00:00',
                'turnaround_hours' => 6.75,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 19.8,
                'estimated_tonnage' => 7.9,
                'severity' => 'critical',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9015',
                'status' => 'resolved',
                'clenro_action_taken' => 'Higalaay Festival riverbank parade spectator garbage combined with market overflow. Quick night mobilization.',
                'decision_recommendation' => 'Deploy specialized street-sweeping support vehicle along bridge approach during festival days.',
                'reported_by' => 'CLENRO Festival Taskforce',
            ],
            [
                'incident_code' => 'CDO-CRM-2024-1115',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Macanhan Commercial Border / Market Rear Exit',
                'latitude' => 8.4819000,
                'longitude' => 124.6349000,
                'incident_date' => '2024-11-15 19:30:00',
                'cleared_date' => '2024-11-17 08:00:00',
                'turnaround_hours' => 36.50,
                'sla_status' => 'breached_48h',
                'waste_volume_m3' => 16.5,
                'estimated_tonnage' => 6.6,
                'severity' => 'critical',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'unauthorized_vendor_dumping',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4105',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Unauthorized vegetable dumping in rear alley ignored by hauler for 36 hours. Deducted ₱25,000 from monthly billing.',
                'decision_recommendation' => 'Install solar-powered CCTV camera at rear exit alley; schedule dual daily sweeps (6:00 AM and 6:00 PM).',
                'reported_by' => 'CLENRO Enforcement Division',
            ],
            [
                'incident_code' => 'CDO-CRM-2025-0106',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Carmen Public Market - Vamenta Blvd Frontage',
                'latitude' => 8.4831200,
                'longitude' => 124.6364500,
                'incident_date' => '2025-01-06 20:00:00',
                'cleared_date' => '2025-01-07 03:15:00',
                'turnaround_hours' => 7.25,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 13.0,
                'estimated_tonnage' => 5.2,
                'severity' => 'high',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4105',
                'status' => 'resolved',
                'clenro_action_taken' => 'Post-Three Kings retail packaging pile cleared overnight without delay.',
                'decision_recommendation' => 'Standard night collection routine effective; maintain route priority.',
                'reported_by' => 'Carmen Market Supervisor',
            ],
            [
                'incident_code' => 'CDO-CRM-2025-0520',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Seriña St. Mid-Market Junction',
                'latitude' => 8.4827000,
                'longitude' => 124.6360000,
                'incident_date' => '2025-05-20 18:45:00',
                'cleared_date' => '2025-05-21 07:00:00',
                'turnaround_hours' => 12.25,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 9.5,
                'estimated_tonnage' => 3.8,
                'severity' => 'moderate',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9015',
                'status' => 'resolved',
                'clenro_action_taken' => 'Afternoon sweep team was understaffed; morning replacement team cleared pile.',
                'decision_recommendation' => 'Rebalance market sweeper shifts so that 60% of personnel are assigned to 3 PM - 11 PM window.',
                'reported_by' => 'CLENRO Sanitation Division',
            ],
            [
                'incident_code' => 'CDO-CRM-2025-0912',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Carmen Bridge Approach (West Bank Riverside)',
                'latitude' => 8.4837500,
                'longitude' => 124.6385000,
                'incident_date' => '2025-09-12 17:30:00',
                'cleared_date' => '2025-09-13 14:00:00',
                'turnaround_hours' => 20.50,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 15.2,
                'estimated_tonnage' => 6.1,
                'severity' => 'critical',
                'waste_category' => 'drainage_canal_debris',
                'root_cause' => 'monsoon_drainage_blockage',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4105',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Heavy rainfall caused riverbank culvert backflow, depositing market plastic waste. Cleared with backhoe support.',
                'decision_recommendation' => 'Install trash boom along Carmen market creek outlet before October habagat storms.',
                'reported_by' => 'CLENRO River Watch Unit',
            ],
            [
                'incident_code' => 'CDO-CRM-2026-0128',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Carmen Public Market - Vamenta Blvd Frontage',
                'latitude' => 8.4831000,
                'longitude' => 124.6364000,
                'incident_date' => '2026-01-28 20:10:00',
                'cleared_date' => '2026-01-29 02:30:00',
                'turnaround_hours' => 6.33,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 12.8,
                'estimated_tonnage' => 5.1,
                'severity' => 'high',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4105',
                'status' => 'resolved',
                'clenro_action_taken' => 'Regular nightly pickup executed on time.',
                'decision_recommendation' => 'Maintain current schedule.',
                'reported_by' => 'Carmen Market Supervisor',
            ],

            // ==========================================
            // URBAN CORE POBLACION (BARANGAY 1 TO 40)
            // ==========================================
            [
                'incident_code' => 'CDO-B01-2024-0305',
                'location_zone' => 'Barangay 1',
                'barangay_number' => 1,
                'specific_landmark' => 'Burgos St. Riverwall & City Hall Perimeter',
                'latitude' => 8.4745000,
                'longitude' => 124.6432000,
                'incident_date' => '2024-03-05 08:30:00',
                'cleared_date' => '2024-03-05 14:00:00',
                'turnaround_hours' => 5.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 6.2,
                'estimated_tonnage' => 2.4,
                'severity' => 'moderate',
                'waste_category' => 'household_unsegregated',
                'root_cause' => 'unauthorized_vendor_dumping',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4101',
                'status' => 'resolved',
                'clenro_action_taken' => 'Bags dumped alongside riverwall walkway. Cleared and warning signage placed.',
                'decision_recommendation' => 'Coordinate with Brgy 1 Tanods for midnight riverwall patrol against illegal dumping.',
                'reported_by' => 'CLENRO Riverbank Monitor',
            ],
            [
                'incident_code' => 'CDO-B02-2024-0518',
                'location_zone' => 'Barangay 2',
                'barangay_number' => 2,
                'specific_landmark' => 'Capistrano St. Corner Gaerlan St.',
                'latitude' => 8.4758000,
                'longitude' => 124.6441000,
                'incident_date' => '2024-05-18 09:00:00',
                'cleared_date' => '2024-05-19 16:30:00',
                'turnaround_hours' => 31.50,
                'sla_status' => 'breached_48h',
                'waste_volume_m3' => 8.4,
                'estimated_tonnage' => 3.2,
                'severity' => 'high',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'delayed_contractor_dispatch',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4101',
                'status' => 'resolved',
                'clenro_action_taken' => 'Contractor missed Saturday morning collection. Commercial boxes spilled onto sidewalk.',
                'decision_recommendation' => 'Fine contractor ₱10,000 for unannounced route cancellation in commercial poblacion.',
                'reported_by' => 'Barangay 2 Secretary',
            ],
            [
                'incident_code' => 'CDO-B07-2024-0825',
                'location_zone' => 'Barangay 7',
                'barangay_number' => 7,
                'specific_landmark' => 'Plaza Divisoria Kiosks (Tirso Neri St.)',
                'latitude' => 8.4770000,
                'longitude' => 124.6450000,
                'incident_date' => '2024-08-25 23:00:00',
                'cleared_date' => '2024-08-26 04:30:00',
                'turnaround_hours' => 5.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 11.5,
                'estimated_tonnage' => 4.6,
                'severity' => 'high',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9014',
                'status' => 'resolved',
                'clenro_action_taken' => 'Post-concert festival cleanup completed before sunrise in Divisoria park.',
                'decision_recommendation' => 'Mandate event organizers to provide private trash receptacles for events exceeding 500 attendees.',
                'reported_by' => 'CLENRO Event Clearing Crew',
            ],
            [
                'incident_code' => 'CDO-B10-2024-1014',
                'location_zone' => 'Barangay 10',
                'barangay_number' => 10,
                'specific_landmark' => 'Apolinar Velez St. Commercial Strip (Near Dolores St.)',
                'latitude' => 8.4762000,
                'longitude' => 124.6462000,
                'incident_date' => '2024-10-14 07:15:00',
                'cleared_date' => '2024-10-14 11:30:00',
                'turnaround_hours' => 4.25,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 5.0,
                'estimated_tonnage' => 1.9,
                'severity' => 'moderate',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4101',
                'status' => 'resolved',
                'clenro_action_taken' => 'Fast-food cartons piled outside commercial bank. Dispatched small compactor.',
                'decision_recommendation' => 'Require commercial establishments along Velez St. to maintain internal trash storage bins.',
                'reported_by' => 'CLENRO Urban Inspector #01',
            ],
            [
                'incident_code' => 'CDO-B14-2024-1229',
                'location_zone' => 'Barangay 14',
                'barangay_number' => 14,
                'specific_landmark' => 'Toribio Chaves St. Corner Tiano Brothers',
                'latitude' => 8.4754000,
                'longitude' => 124.6471000,
                'incident_date' => '2024-12-29 10:00:00',
                'cleared_date' => '2024-12-30 08:30:00',
                'turnaround_hours' => 22.50,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 7.8,
                'estimated_tonnage' => 3.0,
                'severity' => 'high',
                'waste_category' => 'household_unsegregated',
                'root_cause' => 'delayed_contractor_dispatch',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4103',
                'status' => 'resolved',
                'clenro_action_taken' => 'Holiday residential waste buildup on narrow street. Required mini-compactor deployment.',
                'decision_recommendation' => 'Schedule 3 mini-compactor runs per week during Christmas season for narrow urban alleys.',
                'reported_by' => 'Barangay 14 Chairperson',
            ],
            [
                'incident_code' => 'CDO-B21-2025-0211',
                'location_zone' => 'Barangay 21',
                'barangay_number' => 21,
                'specific_landmark' => 'Corrales Ave Near Provincial Capitol Rear',
                'latitude' => 8.4795000,
                'longitude' => 124.6468000,
                'incident_date' => '2025-02-11 08:00:00',
                'cleared_date' => '2025-02-11 13:30:00',
                'turnaround_hours' => 5.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 4.5,
                'estimated_tonnage' => 1.7,
                'severity' => 'moderate',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4103',
                'status' => 'resolved',
                'clenro_action_taken' => 'Routine clearing completed smoothly.',
                'decision_recommendation' => 'Maintain current schedule.',
                'reported_by' => 'CLENRO District 2 Inspector',
            ],
            [
                'incident_code' => 'CDO-B22-2025-0402',
                'location_zone' => 'Barangay 22',
                'barangay_number' => 22,
                'specific_landmark' => 'Bitan-ag Creek Culvert / Luna St. Extension',
                'latitude' => 8.4805000,
                'longitude' => 124.6482000,
                'incident_date' => '2025-04-02 07:30:00',
                'cleared_date' => '2025-04-04 11:00:00',
                'turnaround_hours' => 51.50,
                'sla_status' => 'critical_unresolved',
                'waste_volume_m3' => 13.5,
                'estimated_tonnage' => 5.4,
                'severity' => 'critical',
                'waste_category' => 'drainage_canal_debris',
                'root_cause' => 'monsoon_drainage_blockage',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9016',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Chronic dumping into Bitan-ag Creek culvert obstructed flow. Excavation crew deployed.',
                'decision_recommendation' => 'Install permanent steel trash grates and summon Barangay 22 officials for anti-dumping enforcement hearing.',
                'reported_by' => 'CLENRO Waterways Protection Unit',
            ],
            [
                'incident_code' => 'CDO-B24-2025-0614',
                'location_zone' => 'Barangay 24',
                'barangay_number' => 24,
                'specific_landmark' => 'Apolinar Velez St. - Capitol Park Corner',
                'latitude' => 8.4789000,
                'longitude' => 124.6455000,
                'incident_date' => '2025-06-14 08:30:00',
                'cleared_date' => '2025-06-14 12:45:00',
                'turnaround_hours' => 4.25,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 3.8,
                'estimated_tonnage' => 1.4,
                'severity' => 'low',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4103',
                'status' => 'resolved',
                'clenro_action_taken' => 'Sidewalk trash bins emptied promptly.',
                'decision_recommendation' => 'Routine monitoring sufficient.',
                'reported_by' => 'CLENRO Sweeper Supervisor',
            ],
            [
                'incident_code' => 'CDO-B26-2025-0820',
                'location_zone' => 'Barangay 26',
                'barangay_number' => 26,
                'specific_landmark' => 'Justo Ramonal St. Residential Alley',
                'latitude' => 8.4812000,
                'longitude' => 124.6491000,
                'incident_date' => '2025-08-20 09:15:00',
                'cleared_date' => '2025-08-21 14:00:00',
                'turnaround_hours' => 28.75,
                'sla_status' => 'breached_48h',
                'waste_volume_m3' => 9.2,
                'estimated_tonnage' => 3.6,
                'severity' => 'high',
                'waste_category' => 'household_unsegregated',
                'root_cause' => 'delayed_contractor_dispatch',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4104',
                'status' => 'resolved',
                'clenro_action_taken' => 'Contractor skipped scheduled Tuesday pickup. Barangay captain escalated to CLENRO hotline.',
                'decision_recommendation' => 'Issue official warning to IPM hauling contractor; penalize route supervisor for skipping Brgy 26.',
                'reported_by' => 'Barangay 26 Kagawad on Environment',
            ],
            [
                'incident_code' => 'CDO-B31-2025-1025',
                'location_zone' => 'Barangay 31',
                'barangay_number' => 31,
                'specific_landmark' => 'Yacapin St. / Mortola St. Corner',
                'latitude' => 8.4771000,
                'longitude' => 124.6473000,
                'incident_date' => '2025-10-25 18:30:00',
                'cleared_date' => '2025-10-26 05:00:00',
                'turnaround_hours' => 10.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 8.5,
                'estimated_tonnage' => 3.4,
                'severity' => 'high',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'unauthorized_vendor_dumping',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Storeowners left cardboard & styrofoam boxes on roadway. Cleared during night collection.',
                'decision_recommendation' => 'Strictly enforce store packaging fold-and-tie ordinance to reduce haul volume.',
                'reported_by' => 'CLENRO Commercial Inspector',
            ],
            [
                'incident_code' => 'CDO-B34-2025-1130',
                'location_zone' => 'Barangay 34',
                'barangay_number' => 34,
                'specific_landmark' => 'Osmeña St. Periphery near Cogon Buffer',
                'latitude' => 8.4774000,
                'longitude' => 124.6496000,
                'incident_date' => '2025-11-30 20:00:00',
                'cleared_date' => '2025-12-01 04:30:00',
                'turnaround_hours' => 8.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 12.4,
                'estimated_tonnage' => 5.0,
                'severity' => 'critical',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Spillover waste from Cogon boundary cleared by midnight compactor.',
                'decision_recommendation' => 'Redefine Brgy 34 collection route to sync with Cogon Market night shift sweep.',
                'reported_by' => 'Barangay 34 Tanod Chief',
            ],
            [
                'incident_code' => 'CDO-B35-2025-1215',
                'location_zone' => 'Barangay 35',
                'barangay_number' => 35,
                'specific_landmark' => 'Bitan-ag Creek Footbridge (Hayes St. Access)',
                'latitude' => 8.4760000,
                'longitude' => 124.6498000,
                'incident_date' => '2025-12-15 11:00:00',
                'cleared_date' => '2025-12-16 16:30:00',
                'turnaround_hours' => 29.50,
                'sla_status' => 'breached_48h',
                'waste_volume_m3' => 10.2,
                'estimated_tonnage' => 4.1,
                'severity' => 'high',
                'waste_category' => 'household_unsegregated',
                'root_cause' => 'unauthorized_vendor_dumping',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9016',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Residents dumped household garbage along footbridge railings. Hand-cleared into mini-dump truck.',
                'decision_recommendation' => 'Install community waste station with CCTV and appoint barangay eco-marshal.',
                'reported_by' => 'CLENRO Urban River Patrol',
            ],
            [
                'incident_code' => 'CDO-B39-2026-0110',
                'location_zone' => 'Barangay 39',
                'barangay_number' => 39,
                'specific_landmark' => 'Capt. Vicente Roa St. Periphery / Alleyway 4',
                'latitude' => 8.4767000,
                'longitude' => 124.6491000,
                'incident_date' => '2026-01-10 19:45:00',
                'cleared_date' => '2026-01-11 03:00:00',
                'turnaround_hours' => 7.25,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 8.8,
                'estimated_tonnage' => 3.5,
                'severity' => 'high',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Commercial boxes and fruit trays cleared overnight.',
                'decision_recommendation' => 'Continue joint coordination between Cogon Market administration and Brgy 39 council.',
                'reported_by' => 'CLENRO Night Operations',
            ],
            [
                'incident_code' => 'CDO-B40-2026-0220',
                'location_zone' => 'Barangay 40',
                'barangay_number' => 40,
                'specific_landmark' => 'Guillermo St. Boundary / Mortola St.',
                'latitude' => 8.4762000,
                'longitude' => 124.6477000,
                'incident_date' => '2026-02-20 20:15:00',
                'cleared_date' => '2026-02-21 04:00:00',
                'turnaround_hours' => 7.75,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 7.5,
                'estimated_tonnage' => 3.0,
                'severity' => 'moderate',
                'waste_category' => 'household_unsegregated',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Cleared on scheduled nighttime collection run.',
                'decision_recommendation' => 'Schedule remains optimal.',
                'reported_by' => 'Barangay 40 Kagawad',
            ],
            [
                'incident_code' => 'CDO-B03-2026-0301',
                'location_zone' => 'Barangay 3',
                'barangay_number' => 3,
                'specific_landmark' => 'Fernandez St. Corner Burgos St.',
                'latitude' => 8.4751000,
                'longitude' => 124.6436000,
                'incident_date' => '2026-03-01 09:00:00',
                'cleared_date' => '2026-03-01 13:30:00',
                'turnaround_hours' => 4.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 4.2,
                'estimated_tonnage' => 1.6,
                'severity' => 'moderate',
                'waste_category' => 'household_unsegregated',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4101',
                'status' => 'resolved',
                'clenro_action_taken' => 'Collected prompt on daytime round.',
                'decision_recommendation' => 'Maintain weekly Mon-Wed-Fri morning collection schedule.',
                'reported_by' => 'CLENRO Field Officer #08',
            ],
            [
                'incident_code' => 'CDO-B04-2026-0315',
                'location_zone' => 'Barangay 4',
                'barangay_number' => 4,
                'specific_landmark' => 'Gaerlan St. Near City Central School Outer Wall',
                'latitude' => 8.4764000,
                'longitude' => 124.6445000,
                'incident_date' => '2026-03-15 08:00:00',
                'cleared_date' => '2026-03-15 11:45:00',
                'turnaround_hours' => 3.75,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 3.5,
                'estimated_tonnage' => 1.3,
                'severity' => 'low',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9014',
                'status' => 'resolved',
                'clenro_action_taken' => 'School boundary sidewalk sweep cleared before midday.',
                'decision_recommendation' => 'Coordinate with school administration for segregated campus bins.',
                'reported_by' => 'CLENRO School Zone Coordinator',
            ],
            [
                'incident_code' => 'CDO-B05-2026-0410',
                'location_zone' => 'Barangay 5',
                'barangay_number' => 5,
                'specific_landmark' => 'Capistrano St. Near Ysalina Bridge East Approach',
                'latitude' => 8.4769000,
                'longitude' => 124.6438000,
                'incident_date' => '2026-04-10 07:45:00',
                'cleared_date' => '2026-04-10 12:15:00',
                'turnaround_hours' => 4.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 5.1,
                'estimated_tonnage' => 2.0,
                'severity' => 'moderate',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'unauthorized_vendor_dumping',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4101',
                'status' => 'resolved',
                'clenro_action_taken' => 'Curb sweep completed; issued reminder notice to adjacent retail shop.',
                'decision_recommendation' => 'Issue citation if repeat violation occurs within 30 days.',
                'reported_by' => 'CLENRO Inspector #03',
            ],
            [
                'incident_code' => 'CDO-B12-2026-0504',
                'location_zone' => 'Barangay 12',
                'barangay_number' => 12,
                'specific_landmark' => 'Apolinar Velez St. / Pacana St. Crossing',
                'latitude' => 8.4756000,
                'longitude' => 124.6458000,
                'incident_date' => '2026-05-04 09:30:00',
                'cleared_date' => '2026-05-04 14:00:00',
                'turnaround_hours' => 4.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 4.0,
                'estimated_tonnage' => 1.5,
                'severity' => 'low',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'delayed_contractor_dispatch',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4101',
                'status' => 'resolved',
                'clenro_action_taken' => 'Collected on mid-day makeup run.',
                'decision_recommendation' => 'Ensure contractor driver logs completion on mobile KatokKalinis driver app.',
                'reported_by' => 'CLENRO Dispatch Desk',
            ],
            [
                'incident_code' => 'CDO-B18-2026-0622',
                'location_zone' => 'Barangay 18',
                'barangay_number' => 18,
                'specific_landmark' => 'Toribio Chaves St. Near Dolores St.',
                'latitude' => 8.4748000,
                'longitude' => 124.6465000,
                'incident_date' => '2026-06-22 08:15:00',
                'cleared_date' => '2026-06-22 13:00:00',
                'turnaround_hours' => 4.75,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 3.9,
                'estimated_tonnage' => 1.5,
                'severity' => 'low',
                'waste_category' => 'household_unsegregated',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4103',
                'status' => 'resolved',
                'clenro_action_taken' => 'Sidewalk pile collected on regular schedule.',
                'decision_recommendation' => 'Maintain current schedule.',
                'reported_by' => 'Barangay 18 Official',
            ],
            [
                'incident_code' => 'CDO-B27-2026-0719',
                'location_zone' => 'Barangay 27',
                'barangay_number' => 27,
                'specific_landmark' => 'Corrales Ave Near Hayes St. Culvert',
                'latitude' => 8.4788000,
                'longitude' => 124.6475000,
                'incident_date' => '2026-07-19 10:00:00',
                'cleared_date' => '2026-07-20 09:30:00',
                'turnaround_hours' => 23.50,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 8.9,
                'estimated_tonnage' => 3.5,
                'severity' => 'high',
                'waste_category' => 'drainage_canal_debris',
                'root_cause' => 'monsoon_drainage_blockage',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9016',
                'status' => 'resolved',
                'clenro_action_taken' => 'Post-rain canal clearing pulled waterlogged plastic and silt. Truck dispatched for pickup.',
                'decision_recommendation' => 'Inspect culvert bi-weekly during July-September habagat season.',
                'reported_by' => 'CLENRO Drainage Oversight Team',
            ],
            [
                'incident_code' => 'CDO-B33-2026-0815',
                'location_zone' => 'Barangay 33',
                'barangay_number' => 33,
                'specific_landmark' => 'J.R. Borja St. Corner Guillermo St.',
                'latitude' => 8.4779000,
                'longitude' => 124.6478000,
                'incident_date' => '2026-08-15 21:00:00',
                'cleared_date' => '2026-08-16 03:30:00',
                'turnaround_hours' => 6.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 14.8,
                'estimated_tonnage' => 6.1,
                'severity' => 'critical',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Pre-Higalaay vendor deliveries generated high volume. Cleared via dedicated night compactor.',
                'decision_recommendation' => 'Activate 24-hour festival collection taskforce starting August 20.',
                'reported_by' => 'CLENRO Festival Taskforce',
            ],
            [
                'incident_code' => 'CDO-B06-2024-0414',
                'location_zone' => 'Barangay 6',
                'barangay_number' => 6,
                'specific_landmark' => 'Gomez St. / Pabayo St. Residential Corner',
                'latitude' => 8.4761000,
                'longitude' => 124.6448000,
                'incident_date' => '2024-04-14 08:30:00',
                'cleared_date' => '2024-04-14 13:00:00',
                'turnaround_hours' => 4.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 4.20,
                'estimated_tonnage' => 1.60,
                'severity' => 'moderate',
                'waste_category' => 'household_unsegregated',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4101',
                'status' => 'resolved',
                'clenro_action_taken' => 'Residential garbage collected on morning run.',
                'decision_recommendation' => 'Maintain standard weekly route.',
                'reported_by' => 'Barangay 6 Kagawad',
            ],
            [
                'incident_code' => 'CDO-B08-2024-0824',
                'location_zone' => 'Barangay 8',
                'barangay_number' => 8,
                'specific_landmark' => 'Tirso Neri St. / Divisoria Amphitheater Rear',
                'latitude' => 8.4768000,
                'longitude' => 124.6453000,
                'incident_date' => '2024-08-24 23:30:00',
                'cleared_date' => '2024-08-25 04:30:00',
                'turnaround_hours' => 5.00,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 15.60,
                'estimated_tonnage' => 6.20,
                'severity' => 'critical',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9014',
                'status' => 'resolved',
                'clenro_action_taken' => 'Higalaay street food kiosks generated large plastic cups & food wrapper pile. Night sweep cleared park before 5 AM.',
                'decision_recommendation' => 'Require Divisoria night food vendors to deposit waste directly into roving mini-dump trucks rather than curb staging.',
                'reported_by' => 'CLENRO Park Sanitation Unit',
            ],
            [
                'incident_code' => 'CDO-B09-2024-1110',
                'location_zone' => 'Barangay 9',
                'barangay_number' => 9,
                'specific_landmark' => 'San Agustin Cathedral Perimeter & Fernandez St.',
                'latitude' => 8.4754000,
                'longitude' => 124.6439000,
                'incident_date' => '2024-11-10 11:30:00',
                'cleared_date' => '2024-11-10 16:00:00',
                'turnaround_hours' => 4.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 6.80,
                'estimated_tonnage' => 2.60,
                'severity' => 'moderate',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'unauthorized_vendor_dumping',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4101',
                'status' => 'resolved',
                'clenro_action_taken' => 'Sunday churchgoers and surrounding flower vendors left carton and packaging piles. Afternoon pickup executed.',
                'decision_recommendation' => 'Coordinate with parish administration for cathedral grounds bin segregation.',
                'reported_by' => 'CLENRO Field Officer #04',
            ],
            [
                'incident_code' => 'CDO-B11-2024-1228',
                'location_zone' => 'Barangay 11',
                'barangay_number' => 11,
                'specific_landmark' => 'Tiano Brothers St. Corner Dolores St.',
                'latitude' => 8.4759000,
                'longitude' => 124.6465000,
                'incident_date' => '2024-12-28 09:00:00',
                'cleared_date' => '2024-12-29 08:00:00',
                'turnaround_hours' => 23.00,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 8.40,
                'estimated_tonnage' => 3.30,
                'severity' => 'high',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'delayed_contractor_dispatch',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4103',
                'status' => 'resolved',
                'clenro_action_taken' => 'Post-Christmas commercial retail boxes overflowed onto sidewalk. Contractor delayed morning run.',
                'decision_recommendation' => 'Impose ₱12,500 contractor SLA deduction for 23-hour response breach in downtown commercial corridor.',
                'reported_by' => 'Barangay 11 Sanitation Head',
            ],
            [
                'incident_code' => 'CDO-B13-2025-0118',
                'location_zone' => 'Barangay 13',
                'barangay_number' => 13,
                'specific_landmark' => 'Capistrano St. Night Cafe Corridor / Eateries',
                'latitude' => 8.4752000,
                'longitude' => 124.6443000,
                'incident_date' => '2025-01-18 22:00:00',
                'cleared_date' => '2025-01-19 04:00:00',
                'turnaround_hours' => 6.00,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 10.20,
                'estimated_tonnage' => 4.20,
                'severity' => 'high',
                'waste_category' => 'wet_fish_meat_waste',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9014',
                'status' => 'resolved',
                'clenro_action_taken' => 'Grease-laden food cartons and organic scrap bags cleared by midnight street crew.',
                'decision_recommendation' => 'Mandate grease trap installation and separate food waste barrels for downtown restaurants.',
                'reported_by' => 'CLENRO Sanitation Unit #02',
            ],
            [
                'incident_code' => 'CDO-B15-2025-0310',
                'location_zone' => 'Barangay 15',
                'barangay_number' => 15,
                'specific_landmark' => 'Toribio Chaves St. Near City Health Office',
                'latitude' => 8.4746000,
                'longitude' => 124.6469000,
                'incident_date' => '2025-03-10 08:15:00',
                'cleared_date' => '2025-03-10 12:45:00',
                'turnaround_hours' => 4.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 4.80,
                'estimated_tonnage' => 1.80,
                'severity' => 'moderate',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4103',
                'status' => 'resolved',
                'clenro_action_taken' => 'Collected during morning scheduled run.',
                'decision_recommendation' => 'Maintain current schedule.',
                'reported_by' => 'Barangay 15 Health Officer',
            ],
            [
                'incident_code' => 'CDO-B16-2025-0422',
                'location_zone' => 'Barangay 16',
                'barangay_number' => 16,
                'specific_landmark' => 'Apolinar Velez St. / Cruz Taal St. Junction',
                'latitude' => 8.4775000,
                'longitude' => 124.6460000,
                'incident_date' => '2025-04-22 09:00:00',
                'cleared_date' => '2025-04-23 08:30:00',
                'turnaround_hours' => 23.50,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 7.90,
                'estimated_tonnage' => 3.10,
                'severity' => 'high',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'collection_truck_breakdown',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'KDG-8821',
                'status' => 'resolved',
                'clenro_action_taken' => 'Contractor compactor breakdown halted downtown sector pickup. Backup unit deployed following day.',
                'decision_recommendation' => 'Mandate contractor to dispatch reserve compactor within 2 hours of mechanical breakdown in primary business district.',
                'reported_by' => 'CLENRO Dispatch Officer',
            ],
            [
                'incident_code' => 'CDO-B17-2025-0608',
                'location_zone' => 'Barangay 17',
                'barangay_number' => 17,
                'specific_landmark' => 'Cruz Taal St. Near Rizal Park Fringe',
                'latitude' => 8.4766000,
                'longitude' => 124.6455000,
                'incident_date' => '2025-06-08 08:30:00',
                'cleared_date' => '2025-06-08 13:00:00',
                'turnaround_hours' => 4.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 5.20,
                'estimated_tonnage' => 2.00,
                'severity' => 'moderate',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'unauthorized_vendor_dumping',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9014',
                'status' => 'resolved',
                'clenro_action_taken' => 'Weekend park spectator waste cleared promptly.',
                'decision_recommendation' => 'Install permanent anti-littering signage under CDO Ordinance 13378.',
                'reported_by' => 'CLENRO Park Warden',
            ],
            [
                'incident_code' => 'CDO-B19-2025-0715',
                'location_zone' => 'Barangay 19',
                'barangay_number' => 19,
                'specific_landmark' => 'Gen. Luna St. / Corrales Ave Commercial Intersection',
                'latitude' => 8.4784000,
                'longitude' => 124.6470000,
                'incident_date' => '2025-07-15 10:30:00',
                'cleared_date' => '2025-07-16 11:00:00',
                'turnaround_hours' => 24.50,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 8.60,
                'estimated_tonnage' => 3.40,
                'severity' => 'high',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'delayed_contractor_dispatch',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4103',
                'status' => 'resolved',
                'clenro_action_taken' => 'Commercial waste pile sat uncollected past 24-hour limit. Heavy fines logged.',
                'decision_recommendation' => 'Issue notice of violation and penalty deduction on contractor billing.',
                'reported_by' => 'Barangay 19 Council',
            ],
            [
                'incident_code' => 'CDO-B20-2025-0814',
                'location_zone' => 'Barangay 20',
                'barangay_number' => 20,
                'specific_landmark' => 'T. Chavez St. / Pabayo St. Commercial Corner',
                'latitude' => 8.4749000,
                'longitude' => 124.6458000,
                'incident_date' => '2025-08-14 19:30:00',
                'cleared_date' => '2025-08-15 02:45:00',
                'turnaround_hours' => 7.25,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 6.50,
                'estimated_tonnage' => 2.50,
                'severity' => 'moderate',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'unauthorized_vendor_dumping',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4101',
                'status' => 'resolved',
                'clenro_action_taken' => 'Night patrol caught commercial store dumping waste before collection schedule; issued warning.',
                'decision_recommendation' => 'Eco-Wardens to conduct random nighttime enforcement sweeps.',
                'reported_by' => 'CLENRO Eco-Warden #05',
            ],
            [
                'incident_code' => 'CDO-B23-2025-0925',
                'location_zone' => 'Barangay 23',
                'barangay_number' => 23,
                'specific_landmark' => 'Hayes St. / Mortola St. Junction (Cogon Perimeter)',
                'latitude' => 8.4772000,
                'longitude' => 124.6486000,
                'incident_date' => '2025-09-25 20:00:00',
                'cleared_date' => '2025-09-26 03:30:00',
                'turnaround_hours' => 7.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 13.80,
                'estimated_tonnage' => 5.60,
                'severity' => 'critical',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Vegetable stalls boundary spillover cleared during night sweep.',
                'decision_recommendation' => 'Extend Cogon market compactor coverage 1 block further south into Brgy 23.',
                'reported_by' => 'Barangay 23 Chairperson',
            ],
            [
                'incident_code' => 'CDO-B25-2025-1018',
                'location_zone' => 'Barangay 25',
                'barangay_number' => 25,
                'specific_landmark' => 'Justo Ramonal St. Extension Near Bitan-ag Canal',
                'latitude' => 8.4815000,
                'longitude' => 124.6488000,
                'incident_date' => '2025-10-18 07:00:00',
                'cleared_date' => '2025-10-19 14:00:00',
                'turnaround_hours' => 31.00,
                'sla_status' => 'breached_48h',
                'waste_volume_m3' => 11.20,
                'estimated_tonnage' => 4.50,
                'severity' => 'critical',
                'waste_category' => 'drainage_canal_debris',
                'root_cause' => 'monsoon_drainage_blockage',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9016',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Habagat storm caused canal backflow pushing hundreds of plastic bottles onto sidewalk. Backhoe used.',
                'decision_recommendation' => 'Construct permanent floating trash trap along Justo Ramonal section of Bitan-ag Creek.',
                'reported_by' => 'CLENRO Waterways Protection Unit',
            ],
            [
                'incident_code' => 'CDO-B28-2025-1112',
                'location_zone' => 'Barangay 28',
                'barangay_number' => 28,
                'specific_landmark' => 'Capt. Vicente Roa St. / Provincial Capitol East Gate',
                'latitude' => 8.4792000,
                'longitude' => 124.6472000,
                'incident_date' => '2025-11-12 08:30:00',
                'cleared_date' => '2025-11-12 12:45:00',
                'turnaround_hours' => 4.25,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 4.30,
                'estimated_tonnage' => 1.70,
                'severity' => 'low',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4103',
                'status' => 'resolved',
                'clenro_action_taken' => 'Offices paper and lunch packaging cleared on schedule.',
                'decision_recommendation' => 'Maintain current collection frequency.',
                'reported_by' => 'CLENRO Capitol Liaison',
            ],
            [
                'incident_code' => 'CDO-B29-2025-1220',
                'location_zone' => 'Barangay 29',
                'barangay_number' => 29,
                'specific_landmark' => 'J.R. Borja St. / Corrales Ave Shopping Strip',
                'latitude' => 8.4782000,
                'longitude' => 124.6471000,
                'incident_date' => '2025-12-20 21:00:00',
                'cleared_date' => '2025-12-21 04:00:00',
                'turnaround_hours' => 7.00,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 16.50,
                'estimated_tonnage' => 6.80,
                'severity' => 'critical',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Holiday shopping bags & cartons filled curb lanes. Cleared via back-to-back truck runs.',
                'decision_recommendation' => 'Deploy auxiliary dump truck on J.R. Borja commercial corridor Dec 15 to Jan 5.',
                'reported_by' => 'CLENRO Commercial Desk',
            ],
            [
                'incident_code' => 'CDO-B30-2026-0115',
                'location_zone' => 'Barangay 30',
                'barangay_number' => 30,
                'specific_landmark' => 'Yacapin St. / Velez St. Junction',
                'latitude' => 8.4773000,
                'longitude' => 124.6465000,
                'incident_date' => '2026-01-15 08:00:00',
                'cleared_date' => '2026-01-15 13:00:00',
                'turnaround_hours' => 5.00,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 5.60,
                'estimated_tonnage' => 2.20,
                'severity' => 'moderate',
                'waste_category' => 'household_unsegregated',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4101',
                'status' => 'resolved',
                'clenro_action_taken' => 'Routine residential pickup completed without incident.',
                'decision_recommendation' => 'Maintain current morning route.',
                'reported_by' => 'Barangay 30 Official',
            ],
            [
                'incident_code' => 'CDO-B32-2026-0210',
                'location_zone' => 'Barangay 32',
                'barangay_number' => 32,
                'specific_landmark' => 'Capt. Vicente Roa St. / Osmeña St.',
                'latitude' => 8.4766000,
                'longitude' => 124.6485000,
                'incident_date' => '2026-02-10 19:30:00',
                'cleared_date' => '2026-02-11 02:45:00',
                'turnaround_hours' => 7.25,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 9.70,
                'estimated_tonnage' => 3.90,
                'severity' => 'high',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Fruit vendor discarded peels and rotting produce cleared before morning.',
                'decision_recommendation' => 'Mandate daily fruit stall waste bin segregation.',
                'reported_by' => 'CLENRO Market Inspector #02',
            ],
            [
                'incident_code' => 'CDO-B36-2026-0312',
                'location_zone' => 'Barangay 36',
                'barangay_number' => 36,
                'specific_landmark' => 'Limketkai Drive Perimeter / Bitan-ag Creek Culvert',
                'latitude' => 8.4780000,
                'longitude' => 124.6515000,
                'incident_date' => '2026-03-12 08:00:00',
                'cleared_date' => '2026-03-13 10:30:00',
                'turnaround_hours' => 26.50,
                'sla_status' => 'breached_48h',
                'waste_volume_m3' => 14.50,
                'estimated_tonnage' => 5.80,
                'severity' => 'critical',
                'waste_category' => 'drainage_canal_debris',
                'root_cause' => 'monsoon_drainage_blockage',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9016',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Culvert trash screen choked with styrofoam coolers and shopping bags causing street flooding. Cleared with backhoe.',
                'decision_recommendation' => 'Schedule bi-weekly mechanical desiltation and fine upstream commercial establishments.',
                'reported_by' => 'CLENRO Waterways Protection Unit',
            ],
            [
                'incident_code' => 'CDO-B37-2026-0418',
                'location_zone' => 'Barangay 37',
                'barangay_number' => 37,
                'specific_landmark' => 'Valenzuela St. / Agora Boundary Corridor',
                'latitude' => 8.4820000,
                'longitude' => 124.6525000,
                'incident_date' => '2026-04-18 19:00:00',
                'cleared_date' => '2026-04-19 09:30:00',
                'turnaround_hours' => 14.50,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 11.80,
                'estimated_tonnage' => 4.90,
                'severity' => 'high',
                'waste_category' => 'wet_fish_meat_waste',
                'root_cause' => 'delayed_contractor_dispatch',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'KDG-8821',
                'status' => 'resolved',
                'clenro_action_taken' => 'Fish dealer discarded spoiled seafood crates left overnight on curb. Odor complaints verified by CLENRO.',
                'decision_recommendation' => 'Deduct ₱15,000 contractor liquidated damages for rotting wet waste breach over 12 hours.',
                'reported_by' => 'Barangay 37 Sanitation Warden',
            ],
            [
                'incident_code' => 'CDO-B38-2026-0520',
                'location_zone' => 'Barangay 38',
                'barangay_number' => 38,
                'specific_landmark' => 'Gaabucayan St. / Agora Bus Terminal Approach',
                'latitude' => 8.4835000,
                'longitude' => 124.6535000,
                'incident_date' => '2026-05-20 07:30:00',
                'cleared_date' => '2026-05-20 12:00:00',
                'turnaround_hours' => 4.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 6.90,
                'estimated_tonnage' => 2.70,
                'severity' => 'moderate',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'street_sweeping_backlog',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9014',
                'status' => 'resolved',
                'clenro_action_taken' => 'Bus passenger takeaway containers and drink bottles cleared along highway curb.',
                'decision_recommendation' => 'Direct terminal management to install 4 high-capacity waste segregators at bus exit gates.',
                'reported_by' => 'CLENRO Terminal Inspector',
            ],
            [
                'incident_code' => 'CDO-CGN-2024-0318',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 34,
                'specific_landmark' => 'Yacapin St. Night Produce Stalls Corridor',
                'latitude' => 8.4775000,
                'longitude' => 124.6483000,
                'incident_date' => '2024-03-18 21:00:00',
                'cleared_date' => '2024-03-19 02:30:00',
                'turnaround_hours' => 5.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 21.00,
                'estimated_tonnage' => 8.40,
                'severity' => 'critical',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Post-harvest vegetable deliveries cleared with 2 back-to-back compactor trips.',
                'decision_recommendation' => 'Require vegetable wholesale trucks to bag leaves and stalks inside truck bed.',
                'reported_by' => 'Cogon Market Superintendent',
            ],
            [
                'incident_code' => 'CDO-CGN-2024-0720',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 33,
                'specific_landmark' => 'J.R. Borja St. Monsoon Drain Inlets',
                'latitude' => 8.4781000,
                'longitude' => 124.6477000,
                'incident_date' => '2024-07-20 18:00:00',
                'cleared_date' => '2024-07-21 12:00:00',
                'turnaround_hours' => 18.00,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 17.50,
                'estimated_tonnage' => 7.00,
                'severity' => 'critical',
                'waste_category' => 'drainage_canal_debris',
                'root_cause' => 'monsoon_drainage_blockage',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'KDG-8821',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Rainstorm flooded street stalls; floating produce jammed drain inlets. Special vacuum truck deployed.',
                'decision_recommendation' => 'Construct raised concrete curbs along stall boundaries to prevent garbage drift during flash rains.',
                'reported_by' => 'CLENRO Engineering Liaison',
            ],
            [
                'incident_code' => 'CDO-CGN-2025-0512',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 40,
                'specific_landmark' => 'Guillermo St. Fish Landing Section',
                'latitude' => 8.4765000,
                'longitude' => 124.6480000,
                'incident_date' => '2025-05-12 19:30:00',
                'cleared_date' => '2025-05-13 02:00:00',
                'turnaround_hours' => 6.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 13.50,
                'estimated_tonnage' => 5.80,
                'severity' => 'high',
                'waste_category' => 'wet_fish_meat_waste',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9014',
                'status' => 'resolved',
                'clenro_action_taken' => 'Cleared fish entrails and iced water crates. Washed and sanitized street with chlorine spray.',
                'decision_recommendation' => 'Mandate sealed polyethylene tubs for fish vendors.',
                'reported_by' => 'CLENRO Sanitation Inspector #09',
            ],
            [
                'incident_code' => 'CDO-CGN-2025-0826',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 39,
                'specific_landmark' => 'Capt. Vicente Roa St. Higalaay Night Market',
                'latitude' => 8.4769000,
                'longitude' => 124.6489000,
                'incident_date' => '2025-08-26 23:45:00',
                'cleared_date' => '2025-08-27 04:45:00',
                'turnaround_hours' => 5.00,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 26.50,
                'estimated_tonnage' => 10.80,
                'severity' => 'critical',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9015',
                'status' => 'resolved',
                'clenro_action_taken' => 'Higalaay Festival crowd waste cleared in record 5 hours using dual team sweepers.',
                'decision_recommendation' => 'Deploy 4 additional mobile 1,100L roll-out bins during festival week.',
                'reported_by' => 'CLENRO Festival Taskforce Lead',
            ],
            [
                'incident_code' => 'CDO-CGN-2025-1224',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 34,
                'specific_landmark' => 'Osmeña St. Holiday Wholesale Produce Section',
                'latitude' => 8.4773000,
                'longitude' => 124.6494000,
                'incident_date' => '2025-12-24 21:00:00',
                'cleared_date' => '2025-12-25 03:00:00',
                'turnaround_hours' => 6.00,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 31.00,
                'estimated_tonnage' => 12.50,
                'severity' => 'critical',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Record Christmas Eve produce volume cleared by 3 successive compactor roundtrips.',
                'decision_recommendation' => 'Schedule continuous rolling compactor dispatch every 2 hours on December 23–24.',
                'reported_by' => 'Cogon Market Administration',
            ],
            [
                'incident_code' => 'CDO-CGN-2026-0402',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 33,
                'specific_landmark' => 'J.R. Borja St. Frontage (Near Capt. Vicente Roa)',
                'latitude' => 8.4782000,
                'longitude' => 124.6477000,
                'incident_date' => '2026-04-02 20:30:00',
                'cleared_date' => '2026-04-03 02:45:00',
                'turnaround_hours' => 6.25,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 18.00,
                'estimated_tonnage' => 7.20,
                'severity' => 'high',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4102',
                'status' => 'resolved',
                'clenro_action_taken' => 'Pre-Holy Week market restocking waste cleared smoothly before morning.',
                'decision_recommendation' => 'Maintain current holiday dispatch matrix.',
                'reported_by' => 'CLENRO Market Inspector #04',
            ],
            [
                'incident_code' => 'CDO-CGN-2026-0615',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 34,
                'specific_landmark' => 'Yacapin St. Commercial Alley (Mid-Block)',
                'latitude' => 8.4777000,
                'longitude' => 124.6483500,
                'incident_date' => '2026-06-15 19:30:00',
                'cleared_date' => '2026-06-16 11:00:00',
                'turnaround_hours' => 15.50,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 14.00,
                'estimated_tonnage' => 5.60,
                'severity' => 'high',
                'waste_category' => 'commercial_retail_packaging',
                'root_cause' => 'delayed_contractor_dispatch',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'KDG-8821',
                'status' => 'resolved',
                'clenro_action_taken' => 'Hauler failed evening dispatch. Cleared mid-morning after penalty notification.',
                'decision_recommendation' => 'Enforce liquidated damages deduction of ₱12,500 under Section 14.',
                'reported_by' => 'CLENRO Eco-Warden #07',
            ],
            [
                'incident_code' => 'CDO-CGN-2026-0827',
                'location_zone' => 'Cogon Market Zone',
                'barangay_number' => 39,
                'specific_landmark' => 'Capt. Vicente Roa Night Market Strip',
                'latitude' => 8.4768500,
                'longitude' => 124.6489000,
                'incident_date' => '2026-08-27 23:30:00',
                'cleared_date' => '2026-08-28 04:15:00',
                'turnaround_hours' => 4.75,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 27.50,
                'estimated_tonnage' => 11.20,
                'severity' => 'critical',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9014',
                'status' => 'resolved',
                'clenro_action_taken' => 'Higalaay 2026 festival shopping peak waste cleared under 5 hours. Outstanding team turnaround.',
                'decision_recommendation' => 'Replicate 2026 festival rapid sweep protocol in future annual celebrations.',
                'reported_by' => 'CLENRO Festival Taskforce',
            ],
            [
                'incident_code' => 'CDO-CRM-2024-0415',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Seriña St. Wet Section & Poultry Stalls',
                'latitude' => 8.4827500,
                'longitude' => 124.6359000,
                'incident_date' => '2024-04-15 19:00:00',
                'cleared_date' => '2024-04-16 01:00:00',
                'turnaround_hours' => 6.00,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 12.50,
                'estimated_tonnage' => 5.40,
                'severity' => 'high',
                'waste_category' => 'wet_fish_meat_waste',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4105',
                'status' => 'resolved',
                'clenro_action_taken' => 'Cleared poultry feathers and meat offal; lime powder applied to prevent foul odors.',
                'decision_recommendation' => 'Mandate wet market stalls to pre-treat organic poultry waste with bio-enzyme spray.',
                'reported_by' => 'Carmen Market Health Inspector',
            ],
            [
                'incident_code' => 'CDO-CRM-2024-0722',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Carmen Riverbank Canal Culvert (Near Bridge Foot)',
                'latitude' => 8.4838000,
                'longitude' => 124.6388000,
                'incident_date' => '2024-07-22 17:00:00',
                'cleared_date' => '2024-07-23 15:00:00',
                'turnaround_hours' => 22.00,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 16.00,
                'estimated_tonnage' => 6.50,
                'severity' => 'critical',
                'waste_category' => 'drainage_canal_debris',
                'root_cause' => 'monsoon_drainage_blockage',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4105',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Severe culvert clogging during habagat heavy downpour. Backhoe used to scoop plastic sacks.',
                'decision_recommendation' => 'Install permanent concrete trash boom barrier across Carmen drainage culvert.',
                'reported_by' => 'CLENRO River Watch Team',
            ],
            [
                'incident_code' => 'CDO-CRM-2025-0305',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Carmen Public Market - Vamenta Blvd Frontage',
                'latitude' => 8.4831000,
                'longitude' => 124.6364000,
                'incident_date' => '2025-03-05 20:00:00',
                'cleared_date' => '2025-03-06 01:30:00',
                'turnaround_hours' => 5.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 15.00,
                'estimated_tonnage' => 6.00,
                'severity' => 'high',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4105',
                'status' => 'resolved',
                'clenro_action_taken' => 'Post-closing produce trimmings cleared swiftly before morning boulevard traffic.',
                'decision_recommendation' => 'Maintain 8:00 PM collection dispatch for Vamenta Blvd.',
                'reported_by' => 'Carmen Market Supervisor',
            ],
            [
                'incident_code' => 'CDO-CRM-2025-0827',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Carmen Bridge Approach / Vamenta Blvd Corner',
                'latitude' => 8.4838500,
                'longitude' => 124.6390000,
                'incident_date' => '2025-08-27 22:15:00',
                'cleared_date' => '2025-08-28 03:30:00',
                'turnaround_hours' => 5.25,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 22.00,
                'estimated_tonnage' => 8.80,
                'severity' => 'critical',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9015',
                'status' => 'resolved',
                'clenro_action_taken' => 'Higalaay river festival spectators waste cleared in overnight sweep.',
                'decision_recommendation' => 'Increase temporary festival waste containers along Carmen bridge walkway.',
                'reported_by' => 'CLENRO Festival Taskforce',
            ],
            [
                'incident_code' => 'CDO-CRM-2025-1223',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Macanhan Commercial Border / Market Rear Exit',
                'latitude' => 8.4819500,
                'longitude' => 124.6350000,
                'incident_date' => '2025-12-23 20:30:00',
                'cleared_date' => '2025-12-24 03:00:00',
                'turnaround_hours' => 6.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 24.50,
                'estimated_tonnage' => 9.80,
                'severity' => 'critical',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4105',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Holiday market surge cleared by back-to-back truck dispatches.',
                'decision_recommendation' => 'Position high-capacity mobile dumpster at rear exit during late December peak.',
                'reported_by' => 'Carmen Market Security',
            ],
            [
                'incident_code' => 'CDO-CRM-2026-0318',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Seriña St. Mid-Market Junction',
                'latitude' => 8.4827000,
                'longitude' => 124.6361000,
                'incident_date' => '2026-03-18 18:30:00',
                'cleared_date' => '2026-03-19 10:30:00',
                'turnaround_hours' => 16.00,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 13.00,
                'estimated_tonnage' => 5.60,
                'severity' => 'high',
                'waste_category' => 'wet_fish_meat_waste',
                'root_cause' => 'delayed_contractor_dispatch',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'KDG-8821',
                'status' => 'resolved',
                'clenro_action_taken' => 'Contractor skipped evening pickup, cleared mid-morning after sanitation citation issued.',
                'decision_recommendation' => 'Levy ₱15,000 contractor liquidated damages under Section 14.',
                'reported_by' => 'CLENRO Sanitation Officer #03',
            ],
            [
                'incident_code' => 'CDO-CRM-2026-0510',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Macanhan Border Alley / Market Rear Access',
                'latitude' => 8.4819000,
                'longitude' => 124.6348000,
                'incident_date' => '2026-05-10 19:00:00',
                'cleared_date' => '2026-05-12 03:00:00',
                'turnaround_hours' => 32.00,
                'sla_status' => 'breached_48h',
                'waste_volume_m3' => 14.50,
                'estimated_tonnage' => 5.80,
                'severity' => 'critical',
                'waste_category' => 'household_unsegregated',
                'root_cause' => 'unauthorized_vendor_dumping',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9015',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Illegal dumping in rear alley went unattended over weekend. City sweep team dispatched to clear.',
                'decision_recommendation' => 'Install solar CCTV security camera and impose ₱2,000 fines on caught violators.',
                'reported_by' => 'CLENRO Eco-Warden Enforcement',
            ],
            [
                'incident_code' => 'CDO-CRM-2026-0708',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Carmen Public Market - Vamenta Blvd Frontage',
                'latitude' => 8.4831200,
                'longitude' => 124.6364000,
                'incident_date' => '2026-07-08 18:30:00',
                'cleared_date' => '2026-07-09 13:30:00',
                'turnaround_hours' => 19.00,
                'sla_status' => 'breached_24h',
                'waste_volume_m3' => 15.80,
                'estimated_tonnage' => 6.40,
                'severity' => 'critical',
                'waste_category' => 'drainage_canal_debris',
                'root_cause' => 'monsoon_drainage_blockage',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4105',
                'status' => 'chronic_hotspot',
                'clenro_action_taken' => 'Flash rain washed commercial packaging into curbside catchbasins. Required suction pump & loader.',
                'decision_recommendation' => 'Mandate commercial market tenants to seal all waste containers before 5:00 PM during rainy season.',
                'reported_by' => 'CLENRO Disaster Coordination Desk',
            ],
            [
                'incident_code' => 'CDO-CRM-2026-0828',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Carmen Bridge Foot (Ysalina Approach Corridor)',
                'latitude' => 8.4839000,
                'longitude' => 124.6391000,
                'incident_date' => '2026-08-28 21:30:00',
                'cleared_date' => '2026-08-29 02:30:00',
                'turnaround_hours' => 5.00,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 21.50,
                'estimated_tonnage' => 8.60,
                'severity' => 'critical',
                'waste_category' => 'single_use_plastics',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'City In-House Market Sweep Team',
                'truck_plate' => 'LGU-9015',
                'status' => 'resolved',
                'clenro_action_taken' => 'Higalaay 2026 river parade spectator plastic waste cleared in record time.',
                'decision_recommendation' => 'Maintain dedicated post-festival night fleet allocation.',
                'reported_by' => 'CLENRO Festival Taskforce',
            ],
            [
                'incident_code' => 'CDO-CRM-2026-0902',
                'location_zone' => 'Carmen Market Zone',
                'barangay_number' => null,
                'specific_landmark' => 'Seriña St. Wet Section & Poultry Alleys',
                'latitude' => 8.4828000,
                'longitude' => 124.6358500,
                'incident_date' => '2026-09-02 19:15:00',
                'cleared_date' => '2026-09-03 00:45:00',
                'turnaround_hours' => 5.50,
                'sla_status' => 'within_sla',
                'waste_volume_m3' => 11.50,
                'estimated_tonnage' => 4.60,
                'severity' => 'moderate',
                'waste_category' => 'market_organic_vegetable',
                'root_cause' => 'market_closing_overflow',
                'contractor_assigned' => 'IPM CDO Urban Haulers',
                'truck_plate' => 'ABC-4105',
                'status' => 'resolved',
                'clenro_action_taken' => 'Monthly market cleanup sweep executed on schedule without delays.',
                'decision_recommendation' => 'Continue regular night collection route.',
                'reported_by' => 'Carmen Market Supervisor',
            ],
        ];

        foreach ($data as $record) {
            ClenroPileupReport::create($record);
        }
    }
}
